## global
seed: 131
device: cuda:3
mode: train
best_path: None
debug: False # true means no log in file

## data
data_dir: data
dataset: BJTaxi 
input_length: 35 # 8+9*3
batch_size: 32  # 32 will cause oom
test_batch_size: 32
graph_file: data/BJTaxi/adj_mx.npz # num_nodes: 1024
num_nodes: 1024

len_closeness: 8
len_period: 27
len_trend: 0
num_nodes: 1024

## model 
d_input: 2                  # means inflow and outflow
d_output: 2                 # means inflow and outflow
d_model: 32
dropout: 0.1
percent: 0.1                # augumentation percentage  
shm_temp: 0.5               # temperature for loss of spatial heterogeneity modeling 
nmb_prototype: 50           # number of cluster 
yita: 0.5                   # balance for inflow loss and outflow loss, $yita * inflow + (1 - yita) * outflow$
layers: 3
heads: 2


## train
epochs: 400
lr_init: 0.005
early_stop: True
early_stop_patience: 50
grad_norm: True
max_grad_norm: 5
use_dwa: True         # whether to use dwa for loss balance
temp: 2               # tempurature parameter in dwa, a larger T means more similer weights
MMI: False
lr_patience: 20
lr_mode: add
